@ Contest move effect descriptions

gText_HighlyAppealingMove:: @ 827CB82
	.string "Une démo très convaincante.$"

gText_UserMoreEasilyStartled:: @ 827CB9B
	.string "Le POKéMON est facilement\n"
	.string "effrayé après cette démo.$"

gText_GreatAppealButNoMoreToEnd:: @ 827CBCE
	.string "Plaît énormément, mais ne\n"
	.string "permet plus aucune démo.$"

gText_UsedRepeatedlyWithoutBoringJudge:: @ 827CC03
	.string "Peut être utilisé plusieurs\n"
	.string "fois sans ennuyer le JUGE.$"

gText_AvoidStartledByOthersOnce:: @ 827CC34
	.string "Peut éviter une fois d'être\n"
	.string "effrayé par les autres.$"

gText_AvoidStartledByOthers:: @ 827CC5D
	.string "Peut éviter d'être effrayé\n"
	.string "par les autres.$"

gText_AvoidStartledByOthersLittle:: @ 827CC81
	.string "Peut un peu éviter d'être\n"
	.string "effrayé par les autres.$"

gText_UserLessLikelyStartled:: @ 827CCAE
	.string "Le POKéMON a moins de\n"
	.string "chances d'être effrayé.$"

gText_SlightlyStartleFrontMon:: @ 827CCE7
	.string "Effraie légèrement le\n"
	.string "POKéMON précédent.$"

gText_SlightlyStartleAppealed:: @ 827CD0F
	.string "Effraie légèrement ceux\n"
	.string "qui ont déjà fait leur démo.$"

gText_StartleAppealedBeforeUser:: @ 827CD3F
	.string "Effraie le POKéMON ayant\n"
	.string "fait sa démo avant.$"

gText_StartleAllAppealed:: @ 827CD73
	.string "Effraie les POKéMON ayant\n"
	.string "fait leur démonstration.$"

gText_BadlyStartleFrontMon:: @ 827CDA6
	.string "Effraie beaucoup le\n"
	.string "POKéMON précédent.$"

gText_BadlyStartleAppealed:: @ 827CDCB
	.string "Effraie beaucoup ceux\n"
	.string "qui ont déjà fait leur démo.$"

gText_StartleAppealedBeforeUser2:: @ 827CDF8
	.string "Effraie le POKéMON ayant\n"
	.string "fait sa démo avant.$"

gText_StartleAllAppealed2:: @ 827CE2C
	.string "Effraie tous les POKéMON\n"
	.string "ayant fait leur démo avant.$"

gText_ShiftJudgesAttentionFromOthers:: @ 827CE5F
	.string "Détourne l'attention du\n"
	.string "JUGE des autres POKéMON.$"

gText_StartleMonHasJudgesAttention:: @ 827CE89
	.string "Effraie le POKéMON qui\n"
	.string "a l'attention du JUGE.$"

gText_JamOthersMissesTurn:: @ 827CEBE
	.string "Bloque les autres, mais\n"
	.string "perd un tour de démo.$"

gText_StartleMonsMadeSameTypeAppeal:: @ 827CEEF
	.string "Effraie ceux ayant exécuté\n"
	.string "une démo du même type.$"

gText_BadlyStartleCoolAppeals:: @ 827CF1E
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo SG-FD.$"

gText_BadlyStartleBeautyAppeals:: @ 827CF4D
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo BEAUTE.$"

gText_BadlyStartleCuteAppeals:: @ 827CF7E
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo GRACE.$"

gText_BadlyStartleSmartAppeals:: @ 827CFAD
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo INTEL.$"

gText_BadlyStartleToughAppeals:: @ 827CFDD
	.string "Effraie beaucoup ceux qui\n"
	.string "ont fait une démo ROBUS.$"

gText_MakeMonAfterUserNervous:: @ 827D00D
	.string "Rend nerveux le POKéMON\n"
	.string "suivant.$"

gText_MakeAllMonsAfterUserNervous:: @ 827D037
	.string "Rend nerveux tous les\n"
	.string "POKéMON suivants.$"

gText_WorsenConditionOfThoseMadeAppeals:: @ 827D061
	.string "Diminue la condition de\n"
	.string "ceux qui ont fait une démo.$"

gText_BadlyStartleMonsGoodCondition:: @ 827D093
	.string "Effraie beaucoup ceux qui\n"
	.string "sont en bonne condition.$"

gText_AppealGreatIfPerformedFirst:: @ 827D0BD
	.string "Cette démo plaît beaucoup\n"
	.string "si on l'exécute en premier.$"

gText_AppealGreatIfPerformedLast:: @ 827D0E8
	.string "Cette démo plaît beaucoup\n"
	.string "si on l'exécute en dernier.$"

gText_AppealAsGoodAsThoseBeforeIt:: @ 827D112
	.string "Rend la démo aussi réussie\n"
	.string "que les précédentes.$"

gText_AppealAsGoodAsOneBeforeIt:: @ 827D13F
	.string "Rend la démo aussi réussie\n"
	.string "que la précédente.$"

gText_AppealBetterLaterItsPerformed:: @ 827D16E
	.string "Plus cette démo est lancée\n"
	.string "tard, plus elle est réussie.$"

gText_AppealVariesDependingOnTiming:: @ 827D1A1
	.string "La qualité de la démo\n"
	.string "dépend de son timing.$"

gText_WorksWellIfSameTypeAsBefore:: @ 827D1D6
	.string "Démo réussie si du même\n"
	.string "type que la précédente.$"

gText_WorksWellIfDifferentTypeAsBefore:: @ 827D20A
	.string "Démo réussie si de type\n"
	.string "différent de la précédente.$"

gText_AffectedByAppealInFront:: @ 827D23F
	.string "Dépend de la façon dont la\n"
	.string "démo précédente se passe.$"

gText_UpsConditionHelpsPreventNervousness:: @ 827D26E
	.string "Monte la condition.\n"
	.string "Empêche d'être nerveux.$"

gText_AppealWorksWellIfConditionGood:: @ 827D2A3
	.string "Démo réussie si la condi-\n"
	.string "tion du POKéMON est bonne.$"

gText_NextAppealMadeEarlier:: @ 827D2DA
	.string "Prochaine démo exécutée\n"
	.string "plus tôt au tour suivant.$"

gText_NextAppealMadeLater:: @ 827D309
	.string "Prochaine démo exécutée\n"
	.string "plus tard au tour suivant.$"

gText_TurnOrderMoreEasilyScrambled:: @ 827D336
	.string "Facilite le changement des\n"
	.string "passages du prochain tour.$"

gText_ScrambleOrderOfNextAppeals:: @ 827D369
	.string "Mélange l'ordre de passage\n"
	.string "des démos du prochain tour.$"

gText_AppealExcitesAudienceInAnyContest:: @ 827D39A
	.string "Une démo qui enthousiasme\n"
	.string "le public de tout CONCOURS.$"

gText_BadlyStartlesMonsGoodAppeals:: @ 827D3CE
	.string "Effraie beaucoup tous les\n"
	.string "POKéMON qui ont plu.$"

gText_AppealBestMoreCrowdExcited:: @ 827D401
	.string "La démo est plus réussie si\n"
	.string "le public est enthousiaste.$"

gText_TemporarilyStopCrowdExcited:: @ 827D436
	.string "Empêche provisoirement le\n"
	.string "public d'être enthousiaste.$"

@ Unused move names

gText_RainDance:: @ 827D468
	.string "DANSE PLUIE$"

gText_Rage:: @ 827D473
	.string "FRENESIE$"

gText_FocusEnergy:: @ 827D478
	.string "PUISSANCE$"

gText_Hypnosis:: @ 827D485
	.string "HYPNOSE$"

gText_Softboiled:: @ 827D48E
	.string "E-COQUE$"

gText_HornAttack:: @ 827D499
	.string "KOUD'KORNE$"

gText_SwordsDance:: @ 827D4A5
	.string "DANSE-LAMES$"

gText_Conversion:: @ 827D4B2
	.string "ADAPTATION$"

gText_SunnyDay:: @ 827D4BD
	.string "ZENITH$"

gText_Rest2:: @ 827D4C7
	.string "REPOS$"

gText_Vicegrip:: @ 827D4CC
	.string "FORCE POIGNE$"

gText_DefenseCurl:: @ 827D4D5
	.string "BOUL'ARMURE$"

gText_LockOn:: @ 827D4E2
	.string "VERROUILLAGE$"

@ Contest type names

gContestMoveTypeCoolText:: @ 827D4EA
	.string "SG-FD$"

gContestMoveTypeBeautyText:: @ 827D4EF
	.string "BEAUTE$"

gContestMoveTypeCuteText:: @ 827D4F6
	.string "GRACE$"

gContestMoveTypeSmartText:: @ 827D4FB
	.string "INTEL.$"

gContestMoveTypeToughText:: @ 827D501
	.string "ROBUS.$"

gText_AppealNumWhichMoveWillBePlayed:: @ 827D507
	.string "Démonstration nº {STR_VAR_1}!\n"
	.string "Ce sera quelle capacité?$"

gText_AppealNumButItCantParticipate:: @ 827D531
	.string "Démonstration nº {STR_VAR_1}!\n"
	.string "Il ne peut pas participer!$"

gText_MonAppealedWithMove:: @ 827D55A
	.string "{STR_VAR_1} exécute\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers:: @ 827D56F
	.string "{STR_VAR_1} was watching\n"
	.string "les autres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime:: @ 827D597
	.string "Le concours est \n"
	.string "terminé!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed:: @ 827D5C1
	.string "Mais la démonstration\n"
	.string "est bloquée.$"

gText_FollowedAnotherMonsLead:: @ 827D5DC
	.string "Il a suivi l'exemple d'un\n"
	.string "autre POKéMON.$"

gText_ButItMessedUp:: @ 827D600
	.string "Mais ça n'a pas marché.$"

gText_WentBetterThanUsual:: @ 827D612
	.string "C'est mieux que\n"
	.string "d'habitude.$"

gText_JudgeLookedAwayForSomeReason:: @ 827D62D
	.string "Le JUGE a détourné\n"
	.string "le regard.$"

gText_WorkedHardToBuildOnPastMistakes:: @ 827D654
	.string "Il a travaillé dur pour\n"
	.string "réparer ses erreurs.$"

gText_CantMakeAnyMoreMoves:: @ 827D67E
	.string "Il ne peut plus bouger.$"

gText_WorkedFrighteninglyWell:: @ 827D69C
	.string "Ça a super bien \n"
	.string "marché.$"

gText_WorkedHardAsStandoutMon:: @ 827D6BA
	.string "C'était aussi bien que le\n"
	.string "POKéMON en tête.$"

gText_JudgedLookedOnExpectantly:: @ 827D6E5
	.string "Le JUGE lance un regard\n"
	.string "intéressé.$"

gText_WorkedRatherWell:: @ 827D706
	.string "Il a plutôt bien réussi.$"

gText_WorkedLittleBetterThanUsual:: @ 827D71D
	.string "C'était un peu mieux\n"
	.string "que d'habitude.$"

@ Round result texts

gText_MonFailedToStandOutAtAll:: @ 827D743
	.string "{STR_VAR_1} n'a pas été\n"
	.string "convaincant du tout…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch:: @ 827D764
	.string "{STR_VAR_1} n'a pas été\n"
	.string "très convaincant…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention:: @ 827D785
	.string "{STR_VAR_1} a un peu\n"
	.string "attiré l'attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention:: @ 827D7A5
	.string "{STR_VAR_1} a beaucoup\n"
	.string "attiré l'attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention:: @ 827D7C8
	.string "{STR_VAR_1} a attiré\n"
	.string "toute l'attention.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal:: @ 827D7E8
	.string "{STR_VAR_1} n'a pas fait\n"
	.string "sa démonstration.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2:: @ 827D805
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString:: @ 827D830
	.string "$"

gText_JudgesViewsOnMonHeldFirm:: @ 827D831
	.string "Le JUGE n'a pas changé\n"
	.string "d'opinion sur {STR_VAR_1}.$"

gText_MonsXChangedPerceptions:: @ 827D855
	.string "{STR_VAR_3} de {STR_VAR_1}\n"
	.string "change de perceptions.$"

gText_MonsAppealEffectWoreOff:: @ 827D872
	.string "L'effet de la démo du\n"
	.string "{STR_VAR_1} se dissipe.$"

gText_SpecialAppealsEffectWoreOff:: @ 827D88F
	.string "L'effet de la démonstra-\n"
	.string "tion spéciale se dissipe.$"

gText_EveryonesAppealsMadeToLookSame:: @ 827D8B5
	.string "Toutes les démonstra-\n"
	.string "tions se ressemblent.$"

gText_CheapenedMonsAppeal:: @ 827D8E4
	.string "Ça a déprécié la démons-\n"
	.string "tration de {STR_VAR_2}.$"

gText_CheapenedAppealOfThoseAhead:: @ 827D8FE
	.string "Les démos des premiers\n"
	.string "ont été dépréciées.$"

gText_StoleAttentionAwayFromMon:: @ 827D926
	.string "Ça a détourné l'attention\n"
	.string "de {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2:: @ 827D947
	.string "Ça a déprécié la démons-\n"
	.string "tration de {STR_VAR_2}.$"

gText_SeverelyCheapenedOtherAppeals:: @ 827D961
	.string "Ça a fortement déprécié\n"
	.string "les autres démos.$"

gText_AnticipationSwelledForMonsAppealNext:: @ 827D986
	.string "Le public a hâte de revoir\n"
	.string "{STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2:: @ 827D9B1
	.string "Les démos des premiers\n"
	.string "ont été dépréciées.$"

gText_CheapenedJudgesFavoriteAppeal:: @ 827D9D9
	.string "Ça a déprécié la démo\n"
	.string "favorite du JUGE.$"

gText_AppealsOfOthersCheapenedByHalf:: @ 827DA03
	.string "Les démos des autres ont\n"
	.string "été dépréciées de moitié.$"

gText_StoodOutToMakeUpForBeingJammed:: @ 827DA31
	.string "Il essaye de compenser \n"
	.string "car il a été bloqué.$"

gText_CantParticipateInAppealsAnyMore:: @ 827DA5B
	.string "Il ne peut plus participer\n"
	.string "aux démonstrations.$"

gText_TouchedJudgeForFantasticAppeal:: @ 827DA85
	.string "Sa superbe démonstration\n"
	.string "a ému le JUGE.$"

gText_AnticipationRoseForUpcomingAppeals:: @ 827DAB2
	.string "Tout le monde a hâte de\n"
	.string "voir la suite.$"

gText_StoodOutAsMuchAsSpecialAppeals:: @ 827DADA
	.string "Aussi bien que les dé-\n"
	.string "monstrations spéciales.$"

gText_StoodOutAsMuchAsMon:: @ 827DB03
	.string "C'est aussi bien que\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable:: @ 827DB1F
	.string "Les démos bloquées\n"
	.string "passent inaperçues.$"

gText_EveryonesAppealsMadeSame:: @ 827DB4E
	.string "Toutes les démonstra-\n"
	.string "tions se ressemblent.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons:: @ 827DB75
	.string "Il est plus conscient\n"
	.string "des autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantMakeAnAppealAfterThis:: @ 827DBB0
	.string "{STR_VAR_1} ne peut rien\n"
	.string "faire après ça.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_SettledDownJustLittleBit:: @ 827DBE0
	.string "Il s'est un petit\n"
	.string "peu calmé.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BecameObliviousToOtherMons:: @ 827DC0F
	.string "Il a oublié la présence\n"
	.string "des autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BecameLessAwareOfOtherMons:: @ 827DC45
	.string "Il a un peu oublié les\n"
	.string "autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StoppedCaringAboutOtherMons:: @ 827DC7C
	.string "Il a arrêté de penser\n"
	.string "aux autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherMons:: @ 827DCB4
	.string "Il a essayé d'effrayer \n"
	.string "les autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToDazzleOthers:: @ 827DCE7
	.string "Il a essayé d'éblouir\n"
	.string "les autres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_JudgeLookedAwayFromMon:: @ 827DD12
	.string "Le JUGE n'a pas\n"
	.string "regardé {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToUnnerveNextMon:: @ 827DD3D
	.string "Il a essayé de troubler\n"
	.string "le prochain POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameNervous:: @ 827DD6F
	.string "{STR_VAR_1} est devenu\n"
	.string "nerveux.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealTriedToUnnerveWaitingMons:: @ 827DD8E
	.string "Il a essayé de troubler\n"
	.string "les POKéMON suivants.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TauntedMonsDoingWell:: @ 827DDC7
	.string "Il s'est moqué des\n"
	.string "POKéMON qui réussissent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonRegainedItsForm:: @ 827DDF2
	.string "{STR_VAR_1} a repris\n"
	.string "sa forme.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToJamMonDoingWell:: @ 827DE14
	.string "Il a essayé de bloquer les\n"
	.string "POKéMON qui réussissent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StandoutMonHustledEvenMore:: @ 827DE44
	.string "{STR_VAR_1}, en tête,\n"
	.string "s'est encore plus démené.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_LargelyUnnoticedMonWorkedHard:: @ 827DE73
	.string "{STR_VAR_1} finit par\n"
	.string "être remarqué.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_WorkedAsMuchAsMonBefore:: @ 827DEA5
	.string "Il a fait aussi bien que\n"
	.string "le POKéMON précédent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell:: @ 827DED9
	.string "La démo du {STR_VAR_1} \n"
	.string "était mauvaise.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_WorkedAsMuchAsPrecedingMon:: @ 827DF02
	.string "Il a réussi aussi bien que\n"
	.string "le POKéMON d'avant.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell2:: @ 827DF3A
	.string "La démo du {STR_VAR_1} \n"
	.string "était mauvaise.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell3:: @ 827DF63
	.string "La démo du {STR_VAR_1} \n"
	.string "était mauvaise.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentSlightlyWell:: @ 827DF8C
	.string "La démo du {STR_VAR_1}\n"
	.string "était à peu près bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentPrettyWell:: @ 827DFB8
	.string "La démo du {STR_VAR_1}\n"
	.string "était plutôt bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentExcellently:: @ 827DFE2
	.string "La démo du {STR_VAR_1}\n"
	.string "était excellente.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWasDud:: @ 827E00C
	.string "La démo du {STR_VAR_1}\n"
	.string "était ratée.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotWorkVeryWell:: @ 827E02F
	.string "La démo du {STR_VAR_1}\n"
	.string "s'est mal passée.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentSlightlyWell2:: @ 827E05F
	.string "La démo du {STR_VAR_1}\n"
	.string "était à peu près bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentPrettyWell2:: @ 827E08B
	.string "La démo du {STR_VAR_1}\n"
	.string "était plutôt bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentVeryWell:: @ 827E0B5
	.string "La démo du {STR_VAR_1}\n"
	.string "était très bonne.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentExcellently2:: @ 827E0DD
	.string "La démo du {STR_VAR_1}\n"
	.string "était excellente.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_SameTypeAsOneBeforeGood:: @ 827E107
	.string "C'est le même type que le\n"
	.string "POKéMON précédent. Bien!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_NotSameTypeAsOneBeforeGood:: @ 827E143
	.string "Ce n'est pas le même type\n"
	.string "que celui d'avant. Bien!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StoodOutMuchMoreThanMonBefore:: @ 827E17F
	.string "C'était beaucoup mieux\n"
	.string "que le POKéMON précédent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_DidntDoAsWellAsMonBefore:: @ 827E1BB
	.string "C'était moins bien que\n"
	.string "le POKéMON précédent.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsConditionRoseAboveUsual:: @ 827E1F3
	.string "La condition du\n"
	.string "{STR_VAR_1} a augmenté!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsHotStatusMadeGreatAppeal:: @ 827E220
	.string "{STR_VAR_1} a réussi\n"
	.string "grâce à son super statut!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MovedUpInLineForNextAppeal:: @ 827E254
	.string "Il passera en premier\n"
	.string "au prochain tour.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MovedBackInLineForNextAppeal:: @ 827E289
	.string "Il passera en dernier\n"
	.string "au prochain tour.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ScrambledUpOrderForNextTurn:: @ 827E2C5
	.string "Il a changé l'ordre pour\n"
	.string "le prochain tour.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_JudgeLookedAtMonExpectantly:: @ 827E2FE
	.string "Le JUGE lance un regard\n"
	.string "intéressé à {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell:: @ 827E32E
	.string "C'était un bon\n"
	.string "combo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell:: @ 827E35B
	.string "C'était un très bon\n"
	.string "combo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently:: @ 827E38D
	.string "C'était un excellent\n"
	.string "combo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze:: @ 827E3C1
	.string "{STR_VAR_1} a réussi à\n"
	.string "détourner les yeux.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt:: @ 827E3EB
	.string "{STR_VAR_1} a réussi à ne\n"
	.string "pas voir ça.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing:: @ 827E416
	.string "Ça ne déstabilise pas\n"
	.string "{STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted:: @ 827E448
	.string "{STR_VAR_1} s'est laissé\n"
	.string "un peu distraire.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon:: @ 827E473
	.string "Il a essayé d'effrayer \n"
	.string "les autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction:: @ 827E4A6
	.string "Distrait, {STR_VAR_1} a\n"
	.string "baissé la tête.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction:: @ 827E4D5
	.string "Distrait, {STR_VAR_1}\n"
	.string "s'est retourné.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry:: @ 827E504
	.string "{STR_VAR_1} n'a pas pu \n"
	.string "s'empêcher de crier.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp:: @ 827E531
	.string "{STR_VAR_1} n'a pas pu\n"
	.string "s'empêcher de sursauter.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction:: @ 827E55A
	.string "Distrait, {STR_VAR_1} a\n"
	.string "trébuché.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove:: @ 827E58A
	.string "{STR_VAR_1} était trop\n"
	.string "nerveux pour bouger.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2:: @ 827E5B2
	.string "Mais ça n'a pas marché.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous:: @ 827E5D0
	.string "Mais il n'a pas rendu\n"
	.string "sa cible nerveuse.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous:: @ 827E606
	.string "Mais il n'a rendu personne\n"
	.string "nerveux.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored:: @ 827E638
	.string "Mais il a été ignoré…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition:: @ 827E658
	.string "Mais il n'a pas pu\n"
	.string "améliorer sa condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal:: @ 827E68B
	.string "Sa démo a été mauvaise\n"
	.string "à cause de sa condition.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected:: @ 827E6C4
	.string "Ça n'a eu aucun effet sur\n"
	.string "{STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal:: @ 827E6E3
	.string "{STR_VAR_1}, décevant, a\n"
	.string "refait la même démo.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat:: @ 827E717
	.string "Succès pour {STR_VAR_3}\n"
	.string "du {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell:: @ 827E73C
	.string "{STR_VAR_3} du\n"
	.string "{STR_VAR_1} ne plaît pas.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing:: @ 827E76A
	.string "Ovation pour {STR_VAR_3}\n"
	.string "du {STR_VAR_1}!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn:: @ 827E793
	.string "{STR_VAR_1} ne peut par-\n"
	.string "ticiper au prochain tour…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention:: @ 827E7BA
	.string "Il a captivé la foule.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon:: @ 827E7EA
	.string "La foule continue de\n"
	.string "regarder {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored:: @ 827E817
	.string "{STR_VAR_2} du\n"
	.string "{STR_VAR_1} est ignoré.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness:: @ 827E837
	.string "timidité$"

gText_Contest_Anxiety:: @ 827E83F
	.string "anxiété$"

gText_Contest_Laziness:: @ 827E847
	.string "paresse$"

gText_Contest_Hesitancy:: @ 827E850
	.string "hésitation$"

gText_Contest_Fear:: @ 827E85A
	.string "peur$"

gText_Contest_Coolness:: @ 827E85F
	.string "SANG-FROID$"

gText_Contest_Beauty:: @ 827E868
	.string "BEAUTE$"

gText_Contest_Cuteness:: @ 827E86F
	.string "GRACE$"

gText_Contest_Smartness:: @ 827E878
	.string "INTEL.$"

gText_Contest_Toughness:: @ 827E882
	.string "ROBUSTESSE$"

@ Unused
gText_Tension:: @ 827E88C
	.string "TENSION$"

gText_CoolMove:: @ 827E894
	.string "Cap. SG-FD$"

gText_BeautyMove:: @ 827E89E
	.string "Cap. BEAUTE$"

gText_CuteMove:: @ 827E8AA
	.string "Cap. GRACE$"

gText_SmartMove:: @ 827E8B4
	.string "Cap. INTEL.$"

gText_ToughMove:: @ 827E8BF
	.string "Cap. ROBUS.$"

gText_3QuestionMarks:: @ 827E8CA
	.string "???$"
