@ Battle Tower
gText_AnabelWonSilver:: @ 82C843F
	.string "C'est très décevant…$"

gText_AnabelDefeatSilver:: @ 82C8458
	.string "D'accord, je vois…$"

gText_AnabelWonGold:: @ 82C846C
	.string "Je suis désolée…$"

gText_AnabelDefeatGold:: @ 82C8480
	.string "Merci…$"

@ Battle Dome
gText_TuckerWonSilver:: @ 82C848B
	.string "Tu n'as pas honte?\n"
	.string "Tout le monde nous regarde!$"

gText_TuckerDefeatSilver:: @ 82C84C1
	.string "Grr…\n"
	.string "Mais…$"

gText_TuckerWonGold:: @ 82C84D0
	.string "Ce n'est pas pour rien qu'on m'appelle\n"
	.string "la STAR DU DOME!$"

gText_TuckerDefeatGold:: @ 82C84F7
	.string "Ha, ha, ha!\n"
	.string "Tu m'amuses!$"

@ Battle Factory
gText_NolandWonSilver:: @ 82C8512
	.string "On t'a donné une bonne leçon, non?$"

gText_NolandDefeatSilver:: @ 82C853B
	.string "Joli travail!\n"
	.string "Tu te débrouilles plutôt bien!$"

gText_NolandWonGold:: @ 82C8561
	.string "Hé, hé, hé!\n"
	.string "C'est déjà fini?$"

gText_NolandDefeatGold:: @ 82C8589
	.string "Je n'y crois pas…$"

@ Battle Pike
gText_LucyWonSilver:: @ 82C859D
	.string "Oh, j'ai gagné…$"

gText_LucyDefeatSilver:: @ 82C85A4
	.string "Oh, j'ai perdu…$"

gText_LucyWonGold:: @ 82C85A9
	.string "Oui!$"

gText_LucyDefeatGold:: @ 82C85AE
	.string "Grrr…$"

@ Battle Arena
gText_GretaWonSilver:: @ 82C85B4
	.string "Tu n'étais pas à fond!\n"
	.string "Tu dois te surpasser!$"

gText_GretaDefeatSilver:: @ 82C85E3
	.string "Pas possible!\n"
	.string "Chapeau!$"

gText_GretaWonGold:: @ 82C85F5
	.string "Hé, hé!\n"
	.string "Mais qu'est-ce que tu espérais?$"

gText_GretaDefeatGold:: @ 82C8611
	.string "Quoi?\n"
	.string "Mais c'est impossible…$"

@ Battle Palace
gText_SpenserWonSilver:: @ 82C8628
	.string "Tes POKéMON sont nuls!\n"
	.string "Et toi, tu es une mauviette!$"

gText_SpenserDefeatSilver:: @ 82C8662
	.string "Ah…\n"
	.string "Je ne m'attendais pas à ça…$"

gText_SpenserWonGold:: @ 82C8682
	.string "Ha, ha, ha!\n"
	.string "Nous ne craignons personne!$"

gText_SpenserDefeatGold:: @ 82C86B3
	.string "Non!\n"
	.string "Ahhhh!!!$"

@ Battle Pyramid
gText_BrandonWonSilver:: @ 82C86C3
	.string "Hé, quel est ton problème?\n"
	.string "Un peu de nerf!$"

gText_BrandonDefeatSilver:: @ 82C86FE
	.string "Bravo! Tu as été superbe!\n"
	.string "Cette victoire, tu la mérites!$"

gText_BrandonWonGold:: @ 82C8739
	.string "Ne baisse pas les bras!\n"
	.string "Tu dois croire en toi!$"

gText_BrandonDefeatGold:: @ 82C877B
	.string "Tu as réussi!\n"
	.string "Tes efforts ont enfin payé!$"
