@ Only contains a portion of the mauville_man text. The rest is in scripts/mauville_man.inc
gText_SoPretty::
	.string " vraiment bien!$"

gText_SoDarling::
	.string " vraiment adorable!$"

gText_SoRelaxed::
	.string " vraiment cool!$"

gText_SoSunny::
	.string " extraordinaire!$"

gText_SoDesirable::
	.string " vraiment fantastique!$"

gText_SoExciting::
	.string " vraiment super!$"

gText_SoAmusing::
	.string " vraiment drôle!$"

gText_SoMagical::
	.string " vraiment magique!$"

gOtherText_Is::
	.string " est$"

gOtherText_DontYouAgree::
	.string "\n"
	.string "Tu es d'accord?$"

gMauvilleManText_ISoWantToGoOnAVacation::
	.string "J'ai vraiment envie d'aller en vacances.\n"
	.string "Il y a un endroit sympa dans le coin?$"

gMauvilleManText_IBoughtCrayonsWith120Colors::
	.string "J'ai acheté des crayons de 120 couleurs\n"
	.string "différentes! Ils sont pas beaux?$"

gMauvilleManText_WouldntItBeNiceIfWeCouldFloat::
	.string "Ne serait-ce pas génial, si on pouvait\n"
	.string "s'envoler sur un nuage de bulles?$"

gMauvilleManText_WhenYouWriteOnASandyBeach::
	.string "Quand on écrit sur du sable, tout est\n"
	.string "effacé par les vagues. C'est triste.$"

gMauvilleManText_WhatsTheBottomOfTheSeaLike::
	.string "J'aimerais aller voir les fonds marins!\n"
	.string "Ça doit être beau, tu crois pas?$"

gMauvilleManText_WhenYouSeeTheSettingSunDoesIt::
	.string "Les couchers de soleil, ça donne envie\n"
	.string "de rentrer chez soi, non?$"

gMauvilleManText_LyingBackInTheGreenGrass::
	.string "S'allonger sur de l'herbe bien verte…\n"
	.string "Waouh, ça c'est super!$"

gMauvilleManText_SecretBasesAreSoWonderful::
	.string "Les BASES SECRETES, c'est génial!\n"
	.string "Non?$"
