ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere: @ 82A7E0E
	.string "Tu as prévu d'aller loin?\p"
	.string "Et si tu m'apportais des SELS TREFONDS\n"
	.string "et des CO. TREFONDS?\p"
	.string "Je peux te préparer quelque chose\n"
	.string "de bon si tu m'apportes ce qu'il faut.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells: @ 82A7EB3
	.string "Si tu m'apportais quatre SELS TREFONDS\n"
	.string "et quatre CO. TREFONDS, je pourrais te\l"
	.string "faire un GRELOT COQUE.\p"
	.string "Tu peux te procurer ces ingrédients\n"
	.string "tous les jours.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell: @ 82A7F37
	.string "Oh, hé! Des SELS TREFONDS et des \n"
	.string "CO. TREFONDS! Et suffisamment!\p"
	.string "Tu veux que je les utilise\n"
	.string "pour faire un GRELOT COQUE?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway: @ 82A7FAC
	.string "Bon, d'accord! Je te fais un\n"
	.string "GRELOT COQUE sur-le-champ.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Voilà! C'est prêt!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell: @ 82A8012
	.string "Gardes-en pour un POKéMON.\n"
	.string "Il va adorer ça, c'est sûr!\p"
	.string "Quoi, le carillon du GRELOT COQUE…\n"
	.string "Sublime!\p"
	.string "Tu peux avoir ses ingrédients tous les\n"
	.string "jours. Alors je peux t'en faire d'autres.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell: @ 82A80C6
	.string "Oh… Dans ce cas…\n"
	.string "Je voulais faire un GRELOT COQUE…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag: @ 82A80F5
	.string "Tu n'as pas assez de place dans ton SAC\n"
	.string "pour recevoir ça.\p"
	.string "Tu devrais faire de la place et\n"
	.string "revenir pour avoir un GRELOT COQUE.$"

ShoalCave_Text_WasShoalSaltNowNothing: @ 82A8169
	.string "Il y avait du SEL TREFONDS ici.\n"
	.string "Mais il n'y a plus rien.$"

ShoalCave_Text_WasShoallShellNowNothing: @ 82A81A8
	.string "Il y avait un CO. TREFONDS ici.\n"
	.string "Mais il n'y a plus rien.$"
